version: "3"

services:
  hadoop-master:
    image: hdfs:latest
    hostname : hadoop-master
    networks:
      - hadoop
    ports:
    - "8088:8088"
    - "50070:50070"
  hadoop-slave1:
    image: hdfs:latest
    hostname: hadoop-slave1
    networks:
      - hadoop
  hadoop-slave2:
    image: hdfs:latest
    hostname: hadoop-slave2
    networks:
      - hadoop

networks:
  hadoop:
